#ifndef __DatabaseViewer__
#define __DatabaseViewer__

/**
@file
Subclass of DatabaseViewer, which is generated by wxFormBuilder.
*/

#include "SteelCalcBase.h"

//// end generated include

/** Implementing DatabaseViewer */
class DatabaseViewer : public DatabaseViewer
{
	public:
		/** Constructor */
		DatabaseViewer( wxWindow* parent );
	//// end generated class members

};

#endif // __DatabaseViewer__
