#ifndef __SteelCalcDatabaseViewer__
#define __SteelCalcDatabaseViewer__

/**
@file
Subclass of DatabaseViewer, which is generated by wxFormBuilder.
*/

#include "SteelCalcBase.h"
#include <SQLiteCpp/Database.h>
#include <SQLiteCpp/Statement.h>

//// end generated include

/** Implementing DatabaseViewer */
class SteelCalcDatabaseViewer : public DatabaseViewer
{
	const std::string	DEFAULT_DATABASE_FILENAME = "database.sq3";
	public:
		/** Constructor */
		SteelCalcDatabaseViewer( wxWindow* parent );
	//// end generated class members
	SteelCalcDatabaseViewer( wxWindow* parent, const std::string& dbFilename, const std::string& tableName);

	private: 
	std::set<std::string> 				DatabaseFetchTableNames(const SQLite::Database& dbConnection)

	std::string							m_dbFilename;
	std::unique_ptr <SQLite::Database>	m_dbConnection;
	std::string							m_dbActiveTableName;
	std::unique_ptr <SQLite::Statement>	m_dbQuery;
};

#endif // __SteelCalcDatabaseViewer__
