#ifndef __SteelCalcMain__
#define __SteelCalcMain__

/**
@file
Subclass of Main, which is generated by wxFormBuilder.
*/

#include "SteelCalcBase.h"
#include <wx/arrstr.h>

//// end generated include

/** Implementing Main */
class SteelCalcMain : public Main
{
	enum ProcessingType
	{
		NoType,
		Stock,
		CB,
		ComplexShape
	};
	public:
		/** Constructor */
		SteelCalcMain( wxWindow* parent );
	//// end generated class members
		// custom constructor declared below here
		SteelCalcMain(wxWindow *parent, wxWindowID id, const wxString &title, const wxPoint &pos, const wxSize &size, long style);

	private:
		// Event handler for grid cell value changes
		double GetBarArea(const wxString& barSpec);
		wxString GetBarProcessingType(const int& numOfValues);
		double GetBarRadius(const wxString& barSpec);
		void Init();
		void OnBarSpecChoiceChanged(wxCommandEvent& event);
		void OnTextCtrlValueChanged(wxFocusEvent& event);
		void OnGridCellValueChanged(wxGridEvent& event);
		void OnCircularInputToggled(wxCommandEvent& event);
		void UpdateResults();
		bool ValidateValue(wxString& value);
		
		// members
		double MASS_N_GRADE_STEEL = 8.051;
		wxString m_processingCurrentBarSize = wxEmptyString;
		wxArrayString m_processingTypes = {_("Enter bar information"), _("Stock"), _("C&&B"), _("Complex Shape")};
		double m_costPerMg = 2200.0; // Cost per Mg placeholder value
};

#endif // __SteelCalcMain__
