#ifndef __SteelCalcMain__
#define __SteelCalcMain__

/**
@file
Subclass of Main, which is generated by wxFormBuilder.
*/

#include "SteelCalcBase.h"

//// end generated include

/** Implementing Main */
class SteelCalcMain : public Main
{
	public:
		/** Constructor */
		SteelCalcMain( wxWindow* parent );
	//// end generated class members
		// custom constructor declared below here
		SteelCalcMain(wxWindow *parent, wxWindowID id, const wxString &title, const wxPoint &pos, const wxSize &size, long style);

	private:
		// Event handler for grid cell value changes
		void OnGridCellValueChanged(wxGridEvent& event);
		void UpdateResults();
};

#endif // __SteelCalcMain__
