#ifndef __SteelCalcOptions__
#define __SteelCalcOptions__

/**
@file
Subclass of Options, which is generated by wxFormBuilder.
*/

#include "SteelCalcBase.h"

//// end generated include

/** Implementing Options */
class SteelCalcOptions : public Options
{
	public:
		/** Constructor */
		SteelCalcOptions( wxWindow* parent );
	//// end generated class members
		bool GetAddLapTies();
		bool GetAddPerimeterTies();
		bool GetAddSetupTies();
	private: 
		// Handlers for Options events.
		void OnClose( wxCloseEvent& event );
};

#endif // __SteelCalcOptions__
