#ifndef __SteelCalcMain__
#define __SteelCalcMain__

/**
@file
Subclass of Main, which is generated by wxFormBuilder.
*/

#include "SteelCalcBase.h"
#include "SteelCalcOptions.h"
#include "SteelCalcDatabaseViewer.h"
#include <wx/arrstr.h>
#include <wx/fileconf.h>
#include <wx/stdpaths.h>
#include <SQLiteCpp/Database.h>
#include <SQLiteCpp/Statement.h>

//// end generated include

// global constants
// dev-note: you CANNOT use wx types in the global space, only std types.
// if you need to use wx types for a global value, you have to make a function that returns the value at runtime
const	double 		APP_VERSION					= 0.2;
const	std::string	DEFAULT_DATABASE_FILENAME	= "database.sq3";

/** Implementing Main */
class SteelCalcMain : public Main
{
	enum ProcessingType
	{
		NoType,
		Stock,
		CB,
		ComplexShape
	};

	public:
		/** Constructor */
		SteelCalcMain( wxWindow* parent );
	//// end generated class members
		// custom constructor declared below here
		SteelCalcMain(wxWindow *parent, wxWindowID id, const wxString &title, const wxPoint &pos, const wxSize &size, long style);

		void			TriggerUpdateResults()	{ UpdateResults(); }
		void			TriggerSaveConfig()		{ SettingsSaveAllToDisk(); }
		wxArrayString	GetBarClassifications()	{ return m_specsGandD->GetStrings(); }

		// pointers to other program frames
		SteelCalcOptions* 				m_optionsFrame		= nullptr;
		SteelCalcDatabaseViewer*		m_dbViewerFrame		= nullptr;

	private:
		void 			Init();
		double			GetBarArea(const wxString& barSpec);
		wxString		GetBarProcessingType(const int& numOfValues);
		double			GetBarRadius(const wxString& barSpec);
		wxString		GetGlobalDefaultConfigFilename();
		void			OnBarSpecChoiceChanged(wxCommandEvent& event);
		void			OnBtnClearAllInputEntries(wxCommandEvent& event);
		void			OnCircularInputToggled(wxCommandEvent& event);
		void			OnClose(wxCloseEvent &event);
		void			OnGridCellValueChanged(wxGridEvent& event);
		void			OnMenuFileAbout(wxCommandEvent& event);
		void			OnMenuFileDatabaseViewer(wxCommandEvent& event);
		void			OnMenuFileOptions(wxCommandEvent& event);
		void			OnMenuFileExit(wxCommandEvent& event);
		void			OnTextCtrlValueChanged(wxFocusEvent& event);
		void			SettingsLoadAllFromDisk();
		void			SettingsSaveAllToDisk();
		void			SettingsSaveBarGradeCostsToDisk(wxFileConfig& configObj);
		void 			UpdateResults();
		bool			ValidateValue(wxString& value);
		
		// members
		std::unique_ptr <SQLite::Database>	m_dbMain;
		std::unique_ptr <SQLite::Statement>	m_dbQuery;
		double								MASS_N_GRADE_STEEL			= 9.180; // placeholder - matches Neumanns calculations afaik
		wxString							m_processingCurrentBarSize	= wxEmptyString;
		wxArrayString						m_processingTypes			= {_("Enter bar information"), _("Stock"), _("C&&B"), _("Complex Shape")};
		double								m_costPerMg					= 2200.0; // Cost per Mg placeholder value
};

#endif // __SteelCalcMain__
