#ifndef __SteelCalcOptions__
#define __SteelCalcOptions__

#include "CustomGridCellEditor.h"

/**
@file
Subclass of Options, which is generated by wxFormBuilder.
*/

//// end generated include

// forward declare the SteelCalcMain class
class SteelCalcMain;

/** Implementing Options */
class SteelCalcOptions : public Options
{
	public:
		/** Constructor */
		SteelCalcOptions( wxWindow* parent );
	//// end generated class members

		bool 									GetAddLapTies();
		bool 									GetAddPerimeterTies();
		bool 									GetAddSetupTies();
		wxVector<std::pair<wxString, wxString>>	GetBarClassificationData();
		void 									SetAddLapTies(const bool& value);
		void 									SetAddPerimeterTies(const bool& value);
		void 									SetAddSetupTies(const bool& value);
		void 									SetBarClassificationData(const wxVector<std::pair<wxString, wxString>>& barData);
	private: 
		// Handlers for Options events.
		// void OnBarClassificationValueChange( wxDataViewEvent& event);
		void	OnClose( wxCloseEvent& event );

		// private members
		wxVector<std::pair<wxString, wxString>>		m_barGradeAndCostData;
		SteelCalcMain*								m_mainFrame;
};

#endif // __SteelCalcOptions__
